kind: pipeline
name: default

steps:
- name: test
  image: plugins/docker
  repo: dommgifer/helloworld
  tag: test
  USERNAME:
    from_secret: docker_username
  PASSWORD:
    from_secret: docker_password
