---
kind: pipeline
type: docker
name: test

steps:
- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: dommgifer/helloworld
    tags: latest

---
kind: pipeline
type: docker
name: test2

steps:
- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: dommgifer/helloworld
    tags: latest1