kind: pipeline
name: default

steps:
- name: test
  image: plugins/docker
  setting:
    repo: dommgifer/helloworld
    tags: test
    USERNAME:
      from_secret: docker_username
    PASSWORD:
      from_secret: docker_password
