build:
  stage: build
  # only:
  #   - dev
  #   - tags
  # image: "registry.gitlab.com/gitlab-org/cluster-integration/auto-build-image:v1.0.0"
  image: docker:20.10.6-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://0.0.0.0:2375"
    CI_APPLICATION_REPOSITORY: $CI_APPLICATION_REPOSITORY
    CI_APPLICATION_TAG: $CI_COMMIT_BRANCH
    CI_REGISTRY: $CI_REGISTRY
    CI_REGISTRY_USER: $CI_REGISTRY_USER
    CI_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD
    HARBOR: $HARBOR
    HARBOR_CERT: $HARBOR_CERT
  # services:
  #   - name: docker:20.10.6-dind
  #     command: ['--tls=false', '--host=tcp://0.0.0.0:2375']
      # entrypoint: ["dockerd-entrypoint.sh"]
      # command: ["--insecure-registry", "harbor.192.168.50.102.nip.io"]
  before_script:
    - mkdir -p /etc/docker/certs.d/$HARBOR/
    - echo "$HARBOR_CERT" | base64 -d > "/etc/docker/certs.d/$HARBOR/ca.crt"
    - docker login $HARBOR -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - sleep 180 
  script:
    # - /build/build.sh
    - docker build -t $CI_APPLICATION_REPOSITORY:$CI_COMMIT_BRANCH .
    - docker push $CI_APPLICATION_REPOSITORY:$CI_COMMIT_BRANCH