build:
  stage: build
  image: "registry.gitlab.com/gitlab-org/cluster-integration/auto-build-image:v0.4.0"
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://localhost:2375"
    CI_APPLICATION_REPOSITORY: $CI_APPLICATION_REPOSITORY
  services:
    - docker:19.03.12-dind
  script:
    - docker build -t $CI_APPLICATION_REPOSITORY:$CI_COMMIT_BRANCH .
    - docker login $HARBOR -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker push $CI_APPLICATION_REPOSITORY:$CI_COMMIT_BRANCH