Deploy:
  stage: deploy
  image: docker:19.03.12
  allow_failure: true
  services:
    - docker:19.03.12-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    KUBECTL_IMAGE: sikalabs/kubectl:latest
    DOCKER_HOST: "tcp://localhost:2375"
    # KUBE_CONFIG: $KUBE_CONFIG
    MOUNT_POINT: /builds/$CI_PROJECT_PATH
  script:
    # - mkdir -p "$MOUNT_POINT"
    - echo $KUBE_CONFIG | base64 -d > $MOUNT_POINT/config
    - docker pull "$KUBECTL_IMAGE"
    - /bin/sleep 600
    - |
      docker run  \
        -v "$MOUNT_POINT:/mnt" \
        $KUBECTL_IMAGE \
        kubectl set image -f /mnt/deployment.yaml hello-world=$CI_APPLICATION_REPOSITORY:$CI_COMMIT_SHA --local -o yaml | kubectl apply --kubeconfig=/mnt/config -f -