Deploy:
  stage: deploy
  image: docker:19.03.12
  allow_failure: true
  services:
    - docker:19.03.12-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    KUBECTL_IMAGE: bitnami/kubectl
    DOCKER_HOST: "tcp://localhost:2375"
  script:
    - echo $KUBE_CONFIG | base64 -d > config
    - docker pull "$KUBECTL_IMAGE"
    - ls -l
    - |
      docker run \
        -v ${pwd}:/.kube $KUBECTL_IMAGE apply -f /.kube/deployment.yaml