Deploy:
  stage: deploy
  image: docker:19.03.12
  allow_failure: true
  services:
    - docker:19.03.12-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    KUBECTL_IMAGE: sikalabs/kubectl:latest
    DOCKER_HOST: "tcp://localhost:2375"
    KUBE_CONFIG: $KUBE_CONFIG
  script:
    - echo $KUBE_CONFIG | base64 -d > config
    - docker pull "$KUBECTL_IMAGE"
    - /bin/sleep 600
    - |
      docker run -it \
        -v "${pwd}:/app" \
        $KUBECTL_IMAGE sleep 600