Deploy:
  stage: deploy
  image: docker:19.03.12
  allow_failure: true
  services:
    - docker:19.03.12-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    KUBECTL_IMAGE: bitnami/kubectl
    DOCKER_HOST: "tcp://localhost:2375"
  script:
    - mkdir -p /.kube
    - echo $KUBE_CONFIG | base64 -d > /.kube/config
    - docker pull "$KUBECTL_IMAGE"
    - ls -l /.kube
    - |
      docker run \
        -v "/.kube:/.kube" \
        -v "${pwd}:/app" $KUBECTL_IMAGE get pod --kubeconfig=/.kube/config