Deploy:
  stage: deploy
  image: buoyantio/kubectl
  allow_failure: true
  variables:
    KUBECONFIG: /.kube/config
  before_script:
    - ls -l
    - mkdir -p $KUBECONFIG
    - echo ${KUBE_CONFIG} | base64 -d > ${KUBECONFIG}
  script:
    - kubectl apply -f deployment.yaml