Deploy:
  stage: deploy
  image: docker:19.03.12
  allow_failure: true
  services:
    - docker:19.03.12-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    KUBECTL_IMAGE: sikalabs/kubectl:latest
    DOCKER_HOST: "tcp://localhost:2375"
  script:
    - mkdir -p /.kube
    - echo $KUBE_CONFIG | base64 -d > /.kube/config
    - docker pull "$KUBECTL_IMAGE"
    - /bin/sleep 600
    - |
      docker run \
        -v /.kube:/root/.kube \
        -v "${pwd}:/app" \
        $KUBECTL_IMAGE bash