Deploy:
  stage: deploy
  image: docker:19.03.12
  allow_failure: true
  services:
    - docker:19.03.12-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    KUBECTL_IMAGE: bitnami/kubectl
    DOCKER_HOST: "tcp://localhost:2375"
  before_script:
    - echo $KUBE_CONFIG | base64 -d > config
  script:
    - docker pull --quiet "$KUBECTL_IMAGE"
    - |
      docker run \
        -v ${pwd}:/bitnami \
        -v $(pwd):/app \
        $KUBECTL_IMAGE --kubeconfig=/bitnami/kubeconfig  apply -f /app/deployment.yaml