Sonarqube:
  stage: sonarqube
  image: docker:19.03.12
  allow_failure: true
  services:
    - docker:19.03.12-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    SONAR_IMAGE: sonarsource/sonar-scanner-cli
    DOCKER_HOST: "tcp://localhost:2375"
  services:
    - docker:19.03.12-dind
  script:
    - docker pull --quiet "$SONAR_IMAGE"
    - |
      docker run \
        -e SONAR_HOST_URL="$SONAR_HOST_URL" \
        -e SONAR_LOGIN="$SONAR_LOGIN" \
        -v "$(pwd):/usr/src" \
        $SONAR_IMAGE  -Dsonar.projectKey=$SONAR_PROJECT
    