apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-helloserver
  labels:
    app: helloserver
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll      
    keel.sh/pollSchedule: "@every 30s"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloserver
  template:
    metadata:
      labels:
        app: helloserver
    spec:
      imagePullSecrets:
      - name: harbor
      containers:
      - name: hello-world
        image: harbor.192.168.50.102.nip.io/demo/hello-world:TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 80
