apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-NAME
  labels:
    app: helloserver-NAME
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll      
    keel.sh/pollSchedule: "@every 30s"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloserver-NAME
  template:
    metadata:
      labels:
        app: helloserver-NAME
    spec:
      imagePullSecrets:
      - name: harbor
      containers:
      - name: hello-world
        image: harbor.192.168.50.102.nip.io/demo/hello-world:TAG
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: helloserver-service-NAME
spec:
  selector:
    app: helloserver-NAME
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80