name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2

#      - name: Build image
#        run: docker build . --file Dockerfile --tag $IMAGE_NAME:$(date +%s)

#      - name: Log into registry
#        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

#      - name: Push image
#        run:  docker push $IMAGE_NAME:$(date +%s)
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Image digest
        env:
          IMAGE_NAME: dommgifer
        run: echo "$IMAGE_NAME":"$(date)"
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/helloworld:$(date)
